#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to your load-balancer IP

valid_subdom()
{
        dig $2.$1 | grep -A1 "ANSWER SECTION:" | awk -v subdom="$2" 'FNR==2 {print "The subdomain " subdom " is a " $4 " record and points to " $5}'
}

if [ $# -eq 2 ];
then
        valid_subdom $1 $2
else
        subdom=('www' 'web-01' 'web-02' 'lb-01')

        for i in "${subdom[@]}";
        do
                valid_subdom $1 $i
        done
fi

