#!/usr/bin/env bash
# Redirect to another page

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html

redirect="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $redirect" /etc/nginx/sites-available/default

service nginx restart
