#!/usr/bin/env bash
# Insert header

sudo apt-get update -y
sudo apt-get -y install nginx
header="add_header X-Served-By $HOSTNAME;"
sudo sed -i "21i$header" /etc/nginx/sites-available/default
sudo service nginx restart
