#!/usr/bin/env bash
#  Create temporary file with PID of this script and handle SIGTERM and
#+ SIGINT. If received SIGTERM or SIGQUIT delete temporary file.

echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT

while true
do
        echo "To infinity and beyond"
        sleep 2
done
