#!/usr/bin/env bash
# This script display the content of the file /etc/passwd
# only displays the:
# username
# group id
# Shell full path for the user

while read
do
        cut -d ':' -f1,4,6
done < /etc/passwd
