#!/usr/bin/env bash
# This script is  displays Holberton School 10 times, but for the 9th iteration,
# displays Holberton School and then Hi on a new line.
i=1
while [ $i -lt 11 ]
do
        if [[ "$i" == 9 ]]; then
                echo 'Holberton School'
                echo 'Hi'
                ((i++))
        else
                echo 'Holberton School'
                ((i++))
        fi
done
