#!/usr/bin/env bash
# This Bash script loops from 1 to a 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations

i=1

while [ $i -lt 11 ]
do
        if [[ "$i" == 4 ]]; then
                echo 'bad luck'
                ((i++))
        elif [[ "$i" == 8 ]]; then
                echo 'good luck'
                ((i++))
        else
                echo 'Holberton School'
                ((i++))
        fi
done
