#!/usr/bin/env bash

# This script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
min=1
while [ $hours -le 12 ]
do
        echo "Hour: $hours"
        min=1
        while [ $min -lt 60 ]
        do
                echo "$min"
                (( min++ ))
        done
        (( hours++ ))
done
