#!/usr/bin/env bash
# Nginx is running as the nginx user

chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod u+x /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
